In [1]:
import pandas as pd
from bs4 import BeautifulSoup as BS
from urllib import request
import numpy as np

wiki = ('https://en.wikipedia.org/wiki/List_of_deadly_earthquakes_since_1900')
result = request.urlopen(wiki)
soup = BS(result.read(), 'html.parser')
t = soup.find_all(class_='wikitable')[0]
df = pd.read_html(str(t), header=0)[0]

print(df)

          Origin (UTC) Present-day country and link to Wikipedia article  \
0     1900-05-11 17:23                                             Japan
1     1900-07-12 06:25                                            Turkey
2     1900-10-29 09:11                                         Venezuela
3     1901-02-15 00:00                                             China
4     1901-03-31 07:11                                          Bulgaria
5     1901-08-09 09:23                                             Japan
6     1901-11-15 20:15         New Zealand (see 1901 Cheviot earthquake)
7     1902-01-30 14:01                                             Japan
8     1902-02-13 09:39                                        Azerbaijan
9     1902-03-09 07:46                                            Turkey
10    1902-04-19 02:23         Guatemala (see 1902 Guatemala earthquake)
11    1902-07-03 15:36                                             China
12    1902-08-22 03:00                                             China
13          1902-09-19                                         Australia
14    1902-12-16 05:07                                        Uzbekistan
15    1903-03-29 22:30                                 Judea and Samaria
16          1903-04-28            Turkey (see 1903 Manzikert earthquake)
17    1903-05-28 03:58                                            Turkey
18    1903-08-11 04:32                                            Greece
19    1903-09-25 01:20                                              Iran
20    1904-04-24 06:39                                            Taiwan
21    1904-08-11 05:56                                            Greece
22    1904-08-30 11:42                                             China
23    1904-11-05 20:25               Taiwan (see 1904 Douliu earthquake)
24    1905-04-04 00:50                                             India
25    1905-06-01 04:42                                           Albania
26    1905-06-02 05:39                                             Japan
27    1905-09-08 01:43              Italy (see 1905 Calabria earthquake)
28    1905-11-08 22:06                                            Greece
29    1906-01-31 15:36    Ecuador (see 1906 Ecuador–Colombia earthquake)
...                ...                                               ...
1310  2008-05-25 08:21                                             China
1311  2008-06-06 20:02                                           Algeria
1312  2008-06-08 12:25          Greece (see 2008 Peloponnese earthquake)
1313  2008-06-13 23:43  Japan (see 2008 Iwate–Miyagi Nairiku earthquake)
1314  2008-06-17 05:51                                             China
1315  2008-07-15 03:26           Greece (see 2008 Dodecanese earthquake)
1316  2008-08-21 12:24            China (see 2008 Yingjiang earthquakes)
1317   2008-08-30 8:30             China (see 2008 Panzhihua earthquake)
1318  2008-10-05 15:52       Kyrgyzstan (see 2008 Kyrgyzstan earthquake)
1319  2008-10-06 16:30               China (see 2008 Damxung earthquake)
1320  2008-10-28 23:09             Pakistan (see 2008 Ziarat earthquake)
1321  2009-01-08 19:21         Costa Rica (see 2009 Cinchona earthquake)
1322  2009-04-06 03:32              Italy (see 2009 L'Aquila earthquake)
1323  2009-07-09 11:19                China (see 2009 Yunnan earthquake)
1324  2009-08-10 20:07              Japan (see 2009 Shizuoka earthquake)
1325  2009-09-02 07:55         Indonesia (see 2009 West Java earthquake)
1326  2009-09-29 17:48     Samoa (see 2009 Samoa earthquake and tsunami)
1327  2009-09-30 10:16            Indonesia (see 2009 Padang earthquake)
1328  2010-01-12 17:00                 Haiti (see 2010 Haiti earthquake)
1329  2010-02-27 06:34                 Chile (see 2010 Chile earthquake)
1330  2010-03-08 02:32               Turkey (see 2010 Elâzığ earthquake)
1331  2010-03-11 14:39             Chile (see 2010 Pichilemu earthquake)
1332  2010-04-14 23:49                 China (see 2010 Yushu earthquake)
1333  2011-02-21 23:51    New Zealand (see 2011 Christchurch earthquake)
1334  2011-03-10 04:58                China (see 2011 Yunnan earthquake)
1335  2011-03-11 14:46                Japan (see 2011 Tōhoku earthquake)
1336  2011-03-24 20:25                 Burma (see 2011 Burma earthquake)
1337  2011-04-07 14:32          Japan (see April 2011 Miyagi earthquake)
1338  2011-09-18 12:40                India (see 2011 Sikkim earthquake)
1339  2011-09-23 10:41                  Turkey (see 2011 Van earthquake)

          Lat      Long Depth (km)    Magnitude Secondary Effects  \
0      38.700   141.100          5     7.0 MJMA               NaN
1      40.300    43.100        NaN      5.9 Muk               NaN
2      11.000   -66.000          0       7.7 Mw               NaN
3      26.000   100.100          0       6.5 Ms               NaN
4      43.400    28.700        NaN      6.4 Muk               NaN
5      40.500   142.500         35       7.2 Mw                 T
6     -43.000   173.000          0       6.8 Ms               NaN
7      40.500   141.300         35       6.9 Ms               NaN
8      40.700    48.600         15      6.9 Muk               NaN
9      40.700    33.600        NaN      5.5 Muk               NaN
10     14.000   -91.000          0       7.5 Mw               NaN
11     43.200   129.600         20       6.7 Ms               NaN
12     40.000    77.000          0       7.7 Mw               NaN
13    -35.000   138.000          2       6.0 ML               NaN
14     40.800    72.300          9      6.4 Muk               NaN
15     32.200    35.300        NaN      5.7 Muk               NaN
16      39.14     42.65        NaN       7.0 Ms               NaN
17     40.900    42.700        NaN      5.8 Muk               NaN
18     36.360    22.970         80      8.3 Muk               NaN
19     35.200    58.200        NaN      6.5 Muk               NaN
20     23.500   120.500        NaN      6.0 Muk               NaN
21     37.750    27.000         10      6.2 Muk               NaN
22     30.000   101.000          0       6.8 Ms               NaN
23     23.500   120.300        NaN      6.3 Muk               NaN
24     33.000    76.000          0       7.8 Mw               NaN
25     42.100    19.600         20      6.6 Muk               NaN
26     34.100   132.500         55       7.0 mb               NaN
27     39.000    16.000          0       6.8 Ms                 T
28     40.000    24.000          0       6.8 Ms               NaN
29      1.000   -81.500          0      8.8 Muk                 T
...       ...       ...        ...          ...               ...
1310   32.560   105.423         18       6.1 Mw                 L
1311   35.883    -0.658          4       5.5 Mw               NaN
1312   37.963    21.525         16       6.4 Mw               NaN
1313   39.030   140.881          7       6.9 Mw                 L
1314   32.761   105.554         10       4.8 mb               NaN
1315   35.983    27.785         68       6.4 Mw               NaN
1316     25.1      97.9        NaN       5.9 Ms               NaN
1317     26.0     101.9         10       5.7 Mw               NaN
1318   39.515    73.768       27.6       6.9 Mw               NaN
1319      NaN       NaN        NaN       6.4 Mw               NaN
1320      NaN       NaN        NaN       6.4 Mw               NaN
1321  10.3962  -84.0281         48       6.1 Mw                 L
1322   42.334    13.334        8.8       6.2 Mw               NaN
1323      NaN       NaN        NaN       5.7 Mw               NaN
1324      NaN       NaN        NaN       6.4 Mw               NaN
1325      NaN       NaN        NaN       7.0 Mw               NaN
1326      NaN       NaN        8.1       8.1 Mw               NaN
1327      NaN       NaN        NaN       7.6 Mw               NaN
1328   18.457   -72.533         13       7.0 Mw               NaN
1329  -35.846   -72.719         35  8.8 Mw [18]                 T
1330      NaN       NaN        NaN       6.1 Mw               NaN
1331      NaN       NaN        NaN       6.9 Mw                 L
1332      NaN       NaN        NaN       6.9 Mw                 L
1333      NaN       NaN        NaN       6.3 Mw                Lq
1334      NaN       NaN        NaN       5.4 Mw               NaN
1335   38.322   142.369       24.4       9.0 Mw                 T
1336      NaN       NaN        NaN       6.8 Mw               NaN
1337     38.2     140.0       66.0       7.1 Mw               NaN
1338   27.723    88.064       19.7       6.9 Mw                 L
1339     38.6      43.5        7.2       7.1 Mw               NaN

      PDE Shaking Deaths  PDE Total Deaths  Utsu Total Deaths  \
0                    NaN               NaN                NaN
1                    NaN               NaN              140.0
2                    NaN               NaN                NaN
3                    NaN               NaN                NaN
4                    NaN               NaN                4.0
5                    NaN               NaN                NaN
6                    NaN               NaN                1.0
7                    NaN               NaN                1.0
8                    NaN               NaN               86.0
9                    NaN               NaN                4.0
10                   NaN               NaN             2000.0
11                   NaN               NaN                NaN
12                   NaN               NaN             5650.0
13                   NaN               NaN                2.0
14                   NaN               NaN             4725.0
15                   NaN               NaN               20.0
16                   NaN               NaN                NaN
17                   NaN               NaN             1000.0
18                   NaN               NaN                2.0
19                   NaN               NaN              200.0
20                   NaN               NaN                3.0
21                   NaN               NaN                4.0
22                   NaN               NaN              565.0
23                   NaN               NaN              145.0
24                   NaN               NaN            20000.0
25                   NaN               NaN              120.0
26                   NaN               NaN               11.0
27                   NaN               NaN              557.0
28                   NaN               NaN                NaN
29                   NaN               NaN             1000.0
...                  ...               ...                ...
1310                 8.0               8.0                NaN
1311                 0.0               1.0                NaN
1312                 2.0               2.0                NaN
1313                13.0              13.0                NaN
1314                 2.0               2.0                NaN
1315                 NaN               NaN                NaN
1316                 NaN               NaN                NaN
1317                 NaN               NaN                NaN
1318                 NaN               NaN                NaN
1319                 NaN               NaN                NaN
1320                 NaN               NaN                NaN
1321                 NaN               NaN                NaN
1322                 NaN               NaN                NaN
1323                 NaN               NaN                NaN
1324                 NaN               NaN                NaN
1325                 NaN               NaN                NaN
1326                 NaN               NaN                NaN
1327                 NaN               NaN                NaN
1328                 NaN               NaN                NaN
1329                 NaN               NaN                NaN
1330                 NaN               NaN                NaN
1331                 NaN               NaN                NaN
1332                 NaN               NaN                NaN
1333                 NaN               NaN                NaN
1334                 NaN               NaN                NaN
1335                 NaN               NaN                NaN
1336                 NaN               NaN                NaN
1337                 NaN               NaN                NaN
1338                 NaN               NaN                NaN
1339                 NaN               NaN                NaN

     EM-DAT Total Deaths           Other Source Deaths
0                    NaN                           NaN
1                    NaN                           NaN
2                    NaN                           NaN
3                    NaN                           NaN
4                    NaN                           NaN
5                    NaN                           NaN
6                    NaN                           NaN
7                    NaN                           NaN
8                    NaN                           NaN
9                    NaN                           NaN
10                  2000                           NaN
11                   NaN                           NaN
12                   NaN                           NaN
13                   NaN                           NaN
14                   NaN                           NaN
15                   NaN                           NaN
16                   NaN                          3500
17                   NaN                           NaN
18                   NaN                           NaN
19                   NaN                           NaN
20                   NaN                           NaN
21                   NaN                           NaN
22                   NaN                           NaN
23                   NaN                           NaN
24                 20000                           NaN
25                   NaN                           NaN
26                   NaN                           NaN
27                  2500                           NaN
28                   NaN                           NaN
29                   400                           NaN
...                  ...                           ...
1310                 NaN                           NaN
1311                 NaN                           NaN
1312                   2                           NaN
1313                  13                           NaN
1314                 NaN                           NaN
1315                 NaN                           NaN
1316                 NaN                           NaN
1317                 NaN                            41
1318                 NaN                        60[16]
1319                 NaN                           NaN
1320                 NaN                           215
1321                 NaN                            34
1322                 NaN                           295
1323                 NaN                           NaN
1324                 NaN                             1
1325                 NaN                            79
1326                 NaN                           189
1327                 NaN                          1115
1328                 NaN                   222,517[17]
1329                 NaN                       521[19]
1330                 NaN                            42
1331                 NaN                             1
1332                 NaN                          2698
1333                 NaN                           181
1334                 NaN                           NaN
1335                 NaN                     15894[20]
1336                 NaN                          150+
1337                 NaN                           NaN
1338                 NaN                          111+
1339                 NaN  601 (as of October 30, 2011)

[1340 rows x 12 columns]

In [11]:
#Making sure we're working with the correct number of columns and rows.  

print(type(df))
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
(1340, 12)

In [9]:
# (1) Pandas automatically fills empty strings with 'NaN.' 

df.head()

,Origin (UTC),Present-day country and link to Wikipedia article,Lat,Long,Depth (km),Magnitude,Secondary Effects,PDE Shaking Deaths,PDE Total Deaths,Utsu Total Deaths,EM-DAT Total Deaths,Other Source Deaths
0,1900-05-11 17:23,Japan,38.700,141.100,5,7.0 MJMA,NaN,NaN,NaN,NaN,NaN,NaN
1,1900-07-12 06:25,Turkey,40.300,43.100,NaN,5.9 Muk,NaN,NaN,NaN,140.0,NaN,NaN
2,1900-10-29 09:11,Venezuela,11.000,-66.000,0,7.7 Mw,NaN,NaN,NaN,NaN,NaN,NaN
3,1901-02-15 00:00,China,26.000,100.100,0,6.5 Ms,NaN,NaN,NaN,NaN,NaN,NaN
4,1901-03-31 07:11,Bulgaria,43.400,28.700,NaN,6.4 Muk,NaN,NaN,NaN,4.0,NaN,NaN

In [4]:
# (2) Dropping the footnotes from 'Other Source Deaths' column.